on:
  workflow_call:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"

  local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'AndresPineros/ReusableWF'
          path: 'ReusableWF'
          ref: ${{ github.head_ref }}

      - uses: ./ReusableWF/local-action

      - uses: actions/checkout@v4

      - shell: bash
        run: ls -laR

      - uses: ./github/actions/local-repo-action